name: Docker Image CI

on:
  release:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      run: | 
        IMAGE_NAME=ghcr.io/cnpem-iot/simar-api:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME
        echo "${{ github.token }}" | docker login ghcr.io -u gfrn --password-stdin
        docker push $IMAGE_NAME
