name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/simar-api:$(date +%s)
        echo "${{ github.token }}" | docker login ghcr.io -u gfrn --password-stdin
        docker push ghcr.io/simar-api:$(date +%s)
